apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__ThorstenHans.SampleApi: "Debug"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
